#pragma once
#include <iostream>  
#include <string>  
#include <math.h>  
#include <stdio.h>  
#include <Windows.h>  
#include <vector>  
#include <thread>  
#include <chrono>  
#include <fstream>  
#include <filesystem>  
#include <map>  
#include <TlHelp32.h>  
#include <d3d11.h>  
#include <dxgi.h>  
#include <dwmapi.h>  
#include <memory>  
#include <numbers>  
#include <mutex>  
#include <cmath>  
#include <functional>  
#include <set>  
#include <WinINet.h>
#include <iomanip>
#include <sstream>
#include <ctime>

#include <stb.h>