#pragma once  
#include <iostream>  
#include <string>  
#include <math.h>  
#include <stdio.h>  
#include <Windows.h>  
#include <vector>  
#include <thread>  
#include <chrono>  
#include <fstream>  
#include <filesystem>  
#include <map>  
#include <TlHelp32.h>  
#include <d3d11.h>  
#include <dxgi.h>  
#include <dwmapi.h>  
#include <memory>  
#include <numbers>  
#include <mutex>  
#include <cmath>  
#include <functional>  
#include <set>  
#include <WinINet.h>
#include <iomanip>
#include <sstream>
#include <ctime>

// libs  
#define IMGUI_DEFINE_MATH_OPERATORS
#include <libs/imgui/imgui.h>  
#include <libs/imgui/imgui_impl_dx11.h>  
#include <libs/imgui/imgui_impl_win32.h>  
#include <libs/imgui/imgui_internal.h>  
#include <libs/stb.h>  
#include <DirectX/d3dx11.h>  
